name: srm_curious_bug
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  firebase_auth: ^4.18.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_white.jpg
    - assets/images/lw_logo_dark.png
    - assets/images/lw_logo_light.png
    - assets/images/srm_logo_wname_dark.png
    - assets/images/srm_logo_wname_light.png
    - assets/images/srm_logo.png
    - assets/images/bluebells.jpg
    - assets/images/google-icon.png
    - assets/icons/calender_icon.png
    - assets/icons/data_icon.png
    - assets/icons/discussion_icon.png
    - assets/icons/down_vote_icon.png
    - assets/icons/emojii_icon.png
    - assets/icons/gallery_icon.png
    - assets/icons/share_icon.png
    - assets/icons/up_vote_icon.png

    




  





    
