name: srm_curious_bug
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  firebase_auth: ^4.18.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

    




  





    
